<link rel="stylesheet" type="text/css" href="../lib_easyui/css/jquery-ui.css"/>
<link rel="stylesheet" type="text/css" href="../lib_easyui/css/color.css">
<link rel="stylesheet" type="text/css" href="../lib_easyui/css/easyui.css">
<link rel="stylesheet" type="text/css" href="../lib_easyui/css/combo.css">
<link rel="stylesheet" type="text/css" href="../lib_easyui/css/icon.css">
<link rel="stylesheet" type="text/css" href="../lib_easyui/css/combobox.css">
<link rel="stylesheet" type="text/css" href="../lib_easyui/css/global.css">
<link rel="stylesheet" type="text/css" href="../lib_easyui/css/demo.css">
<!-- Bootstrap framework -->
<link rel="stylesheet" href="../bootstrap/css/bootstrap.min.css" />
<link rel="stylesheet" href="../bootstrap/css/bootstrap-responsive.min.css" />
